Fix generating swift and objc types when running with Python 3.x
- Previously, trying to generate swift of objc types failed if your system python was 3.x, eg:
   > python -m stone.cli -a host -a style swift_types ...
  would yield this error:
  > TypeError: a bytes-like object is required, not 'str'
- The root cause is that the result of encode() is a bytes-like object, not a string, and the
  code is trying to replace strings within that bytes-like object
- This isn't an issue in python2's version of strings, only 3's
- Fixed by just replacing the characters that need escaping (quote and backslash) instead of trying to encode
- This approach produces identical output to the previous for all current stone files under
  both python2 and python3 environments